export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
export const SET_QUERY = 'SET_QUERY'
export const SET_KEYWORD = 'SET_KEYWORD'
export const SET_COLUMN = 'SET_COLUMN'
export const SET_CATEGORY = 'SET_CATEGORY'

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const GET_CART = 'GET_CART'
export const GET_CART_NUM = 'GET_CART_NUM'

export const GET_SELLERS_LIST = 'GET_SELLERS_LIST'
export const GET_SELLERS_DETAIL = 'GET_SELLERS_DETAIL'

export const GET_MEMBER_INFO = 'GET_SELLERS_DETAIL'
export const GET_COUPON = 'GET_COUPON'

export const STORE_SHIPMENT_FORM = 'STORE_SHIPMENT_FORM'
export const STORE_PAYMENT_FORM = 'STORE_PAYMENT_FORM'

export const GET_POPULAR_PRODUCTS = 'GET_POPULAR_PRODUCTS'
