export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const GET_CART = 'GET_CART'
export const GET_CART_NUM = 'GET_CART_NUM'

export const GET_SELLERS_LIST = 'GET_SELLERS_LIST'
export const GET_SELLERS_DETAIL = 'GET_SELLERS_DETAIL'

export const STORE_SHIPMENT_FORM = 'STORE_SHIPMENT_FORM'
